repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # Use the latest commit SHA / tag
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: '23.11.0'  # Use the latest release version
    hooks:
      - id: black
        language: python
        args: ["--line-length=79"]
  - repo: https://github.com/PyCQA/flake8
    rev: '6.1.0'  # Use the latest release version
    hooks:
      - id: flake8
        name: flake8 under python3
        language_version: python3


# Add other hooks here for tools like isort, mypy, pylint, etc.
